UI Update
CircuitVerse/simple_discussion pull request #1
Opened 2022-12-19 07:26 UTC by Tanmoy741127

This issue was originally referenced in  https://github.com/CircuitVerse/CircuitVerse/issues/3381

#### Describe the changes you have made in this PR -
- Updated the UI of Simple Discussion Forum
- Fixed some broken links issue 
- Added an login bar in thread posts page to let users know to login first before commenting. 

### Screenshots of the changes (If any) -
| Page Name | Screenshot |
|-----------|--------------|
| All Threads | ![image](https://user-images.githubusercontent.com/57363826/208299326-2cd578f9-f471-4aac-8eec-bd1a4841d1dd.png) |
| Thread Details | ![image](https://user-images.githubusercontent.com/57363826/208299835-68bd631f-75ac-4d2b-905d-1772d9698e47.png)|
| Post Edit | ![image](https://user-images.githubusercontent.com/57363826/208299862-8abac3ec-a980-48c9-903b-5cbb561eb8fb.png)|
| New Question | ![image](https://user-images.githubusercontent.com/57363826/208299887-aac39140-0933-4015-b10d-2be3f7eb9297.png) |
| Login Bar | ![image](https://user-images.githubusercontent.com/57363826/208299909-ff78cd75-7a30-4258-bcfb-0a2d99571766.png) | 
| My Questions | ![image](https://user-images.githubusercontent.com/57363826/208299415-7561948f-1aba-42f5-8cec-5dc845339e80.png) |
| Participating | ![image](https://user-images.githubusercontent.com/57363826/208299457-92a869bb-5066-4939-97a5-3b5829b0cd2c.png) |
| Answered | ![image](https://user-images.githubusercontent.com/57363826/208299473-dddd9a38-8c0f-4027-9367-df750a3b6fd0.png) |
| Unanswered | ![image](https://user-images.githubusercontent.com/57363826/208299490-e72078c9-b411-4f8d-a6e2-a287d5cf1ca6.png) | 

### Preview Video

https://user-images.githubusercontent.com/57363826/208299148-e6fb340c-caa8-48ff-971a-0bed30747630.mp4

2022-12-19 07:57 UTC, Tanmoy741127 commented
@tachyons 
take a look. 
As per yesterday's discussion, I have done the updates in this repo through thir PR itself.

And also created an PR https://github.com/CircuitVerse/CircuitVerse/pull/3416 in CircuitVerse for necessary updates .

2022-12-25 10:56 UTC, vedant-jain03 commented
@Tanmoy741127 I have pushed some changes. Check them out and let me know your thoughts on them!

2022-12-25 12:05 UTC, Tanmoy741127 commented
@vedant-jain03 updated a bit . Now everything is good to go. You can check.

2022-12-25 13:13 UTC, tachyons commented on app/helpers/simple_discussion/forum_posts_helper.rb
> -  def avatar_tag(email)
Gravatar no longer in use ?

2022-12-25 13:13 UTC, tachyons commented on app/views/layouts/simple_discussion.html.erb
> +  <h1 class="community-heading">Community</h1>
Make this text i18n compatiable

2022-12-25 13:13 UTC, tachyons commented on app/views/simple_discussion/forum_threads/_forum_thread.html.erb
> +              Solved
Make this i18n compatiable

2022-12-25 13:13 UTC, tachyons commented on app/views/simple_discussion/forum_threads/_login_bar.erb
> +    <a href="/users/sign_up" class="btn forum-primary-btn mx-2"><%= t('create_account') %></a>
Use devise route helpers

2022-12-25 14:05 UTC, Tanmoy741127 commented on app/helpers/simple_discussion/forum_posts_helper.rb
> -  def avatar_tag(email)
Gravatar on use, this specific avatar_tag is not required. Using the `gravatar_url_for` function defined inthatt same file

2022-12-25 14:52 UTC, tachyons commented
@Tanmoy741127 There are a few more places where strings are hardcoded, could you convert them to i18n format ?

2022-12-25 14:58 UTC, vedant-jain03 commented
![Screenshot from 2022-12-25 20-27-21](https://user-images.githubusercontent.com/76901313/209472826-1cc3c20f-1f73-44fb-b1f3-5cd0296c8e1d.png)

The `undo` button needs to be refactored!

2022-12-25 15:03 UTC, Tanmoy741127 commented
@tachyons sure.  I will check and convert them to i18n compatible.

2022-12-25 15:11 UTC, Tanmoy741127 commented
> ![Screenshot from 2022-12-25 20-27-21](https://user-images.githubusercontent.com/76901313/209472826-1cc3c20f-1f73-44fb-b1f3-5cd0296c8e1d.png)
> 
> The `undo` button needs to be refactored!

What changes you prefer ?

2022-12-25 15:29 UTC, Tanmoy741127 commented
> @tachyons sure. I will check and convert them to i18n compatible.

Changes the other strings to i18n compaitable one in  last commit.

2022-12-25 15:31 UTC, Tanmoy741127 commented
> ![Screenshot from 2022-12-25 20-27-21](https://user-images.githubusercontent.com/76901313/209472826-1cc3c20f-1f73-44fb-b1f3-5cd0296c8e1d.png)
> 
> The `undo` button needs to be refactored!

@vedant-jain03 
![image](https://user-images.githubusercontent.com/57363826/209473864-71c2a302-759b-4288-8024-6da1d75e3b57.png)
![image](https://user-images.githubusercontent.com/57363826/209473882-004eadb2-eb39-4c28-b21f-98bf72b5d6ab.png)

Can we use that one or its outlined version ?

2022-12-25 16:33 UTC, vedant-jain03 commented
![Screenshot from 2022-12-25 22-02-36](https://user-images.githubusercontent.com/76901313/209475579-17192c8c-4727-47a0-8e31-33890c4d248f.png)

We have used this button in CircuitVerse groups!

2022-12-25 16:42 UTC, Tanmoy741127 commented
> ![Screenshot from 2022-12-25 22-02-36](https://user-images.githubusercontent.com/76901313/209475579-17192c8c-4727-47a0-8e31-33890c4d248f.png)
> 
> We have used this button in CircuitVerse groups!

Ohh okk

2022-12-25 16:48 UTC, vedant-jain03 requested changes

2022-12-25 16:48 UTC, vedant-jain03 commented on app/views/simple_discussion/user_mailer/new_post.html.erb
> +    <p><strong><%= @forum_post.user.name %></strong> <small><%= t("commented:") %></small></p>
```suggestion
    <p><strong><%= @forum_post.user.name %></strong> <small><%= t("commented") %></small></p>
```

The key should be defined in the `en.yml`.
Keep this for other strings as well!

2022-12-25 16:54 UTC, Tanmoy741127 commented on app/views/simple_discussion/user_mailer/new_post.html.erb
> +    <p><strong><%= @forum_post.user.name %></strong> <small><%= t("commented:") %></small></p>
ok!

2022-12-25 17:04 UTC, Tanmoy741127 commented on app/views/simple_discussion/user_mailer/new_post.html.erb
> +    <p><strong><%= @forum_post.user.name %></strong> <small><%= t("commented:") %></small></p>
@vedant-jain03 updated in latest commit

2022-12-26 12:43 UTC, Tanmoy741127 commented
![forum-first-page (2)](https://user-images.githubusercontent.com/57363826/209550259-e98cbc09-e4c7-4ede-a6f5-33dcc09f9608.png)

@nitin10s has suggested to do the changes (moving the category tags , profile pictures position and removal of unsolved/open tag)
@vedant-jain03 @tachyons  can you see the design attached and confirm any other changes required or not ?

2022-12-26 13:09 UTC, vedant-jain03 commented
> ![forum-first-page (2)](https://user-images.githubusercontent.com/57363826/209550259-e98cbc09-e4c7-4ede-a6f5-33dcc09f9608.png)
> 
> @nitin10s has suggested to do the changes (moving the category tags , profile pictures position and removal of unsolved/open tag) @vedant-jain03 @tachyons can you see the design attached and confirm any other changes required or not ?

LGTM, could you commit the changes?

2022-12-26 13:15 UTC, merged

2022-12-26 13:16 UTC, tachyons commented
@Tanmoy741127 @vedant-jain03 Merged this PR to avoid PR growing too big to review. Please make follow-up PRs for rest of the changes

2022-12-26 13:33 UTC, vedant-jain03 commented
@Tanmoy741127 Great job, thanks 💯

2022-12-26 13:42 UTC, Tanmoy741127 commented
> > ![forum-first-page (2)](https://user-images.githubusercontent.com/57363826/209550259-e98cbc09-e4c7-4ede-a6f5-33dcc09f9608.png)
> > @nitin10s has suggested to do the changes (moving the category tags , profile pictures position and removal of unsolved/open tag) @vedant-jain03 @tachyons can you see the design attached and confirm any other changes required or not ?
> 
> LGTM, could you commit the changes?



> @Tanmoy741127 Great job, thanks 100

Thanks ! Can you open the issues tab for this repo, it can be easy to discuss.