feat(gsoc'24): adding language filter to avoid inappropriate language
CircuitVerse/simple_discussion pull request #24
Opened 2024-06-17 09:53 UTC by Waishnav

solves one of the task of #17

2024-07-21 00:36 UTC, tachyons commented
Good job,

- Could you add tests for this feature ?
- Could you make this feature configurable ?

```ruby

SimpleDiscussion.setup do |config|
  config.send_email_notifications = false # Default: true
  config.send_slack_notifications = false # Default: true
  config.profanity_filter = false # Default: true
end
```

2024-07-21 09:07 UTC, Waishnav commented
> * Could you add tests for this feature ?

![image](https://github.com/user-attachments/assets/fd0b9872-8ce7-44e0-b6e4-2136c9986d61)

I added similar test like this in `/test/integration/forum_test.rb`, but tbh I don't see the usefulness of it, cause no matter what, they are always gonna pass cause these inappriate words are coming from `LanguageFilter` library itself. 
Correct me I might be wrong here?

2024-07-23 12:13 UTC, tachyons requested changes

2024-07-23 12:13 UTC, tachyons commented on Gemfile
> +gem "language_filter"
Since this a runtime dependency, this should be added to the gemspec, not Gemfile

2024-07-23 13:33 UTC, Waishnav commented on Gemfile
> +gem "language_filter"
yeah, since this Gemfile is used for appraisal testing, test were failing that's why I had to add this `language_filter` gem here as well.

2024-07-23 14:44 UTC, tachyons commented on Gemfile
> +gem "language_filter"
@Waishnav That is unlikely, which spec was failing ?

2024-07-23 16:12 UTC, Waishnav commented on Gemfile
> +gem "language_filter"
Checkout the log of this commit.

https://github.com/CircuitVerse/simple_discussion/pull/24/checks?check_run_id=27132581252

2024-07-24 17:21 UTC, tachyons commented on Gemfile
> +gem "language_filter"
@Waishnav That is because you forgot to add require 'language_filter' in the code

2024-07-25 08:46 UTC, Waishnav commented on Gemfile
> +gem "language_filter"
ohh. I guess I missunderstood the significance of Gemfile. Thanks for mentioning it.

I've removed the `language_filter` from Gemfile.

2024-07-25 08:56 UTC, merged